# Generated by Django 5.2.8 on 2026-04-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
