# Generated by Django 5.2.8 on 2026-04-06 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image2_news_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image3',
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/details/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='news.news')),
            ],
        ),
    ]
